server:
  port: 8081

scripts:
  actions:
    test-log:
      description: Тестовый вывод в лог
      type: LOG
      script: |
        new LogAction() {
          void logData(String dataToLog) {
            log.info("info-> " + dataToLog)
          }
        }
    test-log-error:
      description: Тестовый error-экшн
      type: LOG
      script: |
        new LogAction() {
          void logData(String dataToLog) {
            log.error("error-> " + dataToLog)
          }
        }
    test-http:
      description: Тестовый http-экшн
      type: HTTP
      script: |
        new HttpAction() {
          String getUrl() {
            return "http://ya.ru"
          }
        }